language: java

jdk:
 - openjdk8

script: scripts/build.sh

notifications:
 recipients:
  - ethomson@edwardthomson.com
 email:
   on_success: change
   on_failure: always

branches:
  only:
    - master
